### ISSUE TITLE
number of tellers is computed incorrectly for finished stories

### ISSUE THREAD

**Issue by mohrm** [mohrm/umklapp_site#18]
It has to be the total number of tellers which contributed at least one part, not the number of tellers which have not left at the end of the story...

**Comment by mohrm** [comment]
hmm, not as intuitive as I thought...
Maybe also display the total number of tellers and the number of currently active tellers?

**Comment by nomeata** [comment]
I'd be careful introduction many similar numbers. How about: For running stories, display all participating users (as before), for finished stories the number of users that have contributed (as now). At least that's the numbers I'd be interested in.

**Comment by ratefuchs** [comment]
As I see it, we have 4 places where we show such numbers:
1. In the overview, table of running stories
2. In the overview, table of finished stories
3. On viewing a finished story
4. On viewing a running story

For 1., I'd definitely like to see the number of active players (so I have an idea when it might be my turn). For 2., number of contributors is fine, as is for 3. The best number for 4. is more difficult to decide since we might want to choose to be consistent with 1. or 3. Probably we could show both numbers?

**Comment by qznc** [comment]
Something I currently see when viewing running story 55:

> (von DL und 0 weiteren Erzählern)
> Diese Geschichte wird als nächstes von mheck01 weitergeschrieben.

That number 0 is clearly wrong, since we know at least two people here.

**Comment by ratefuchs** [comment]
> Something I currently see when viewing running story 55:
> 
> >    (von DL und 0 weiteren Erzählern)
> >    Diese Geschichte wird als nächstes von mheck01 weitergeschrieben.
> 
> That number 0 is clearly wrong, since we know at least two people here.

SInce we currently show number of people who contributed (i.e. wrote at least one part), for the first teller after the creator we get to see this, so it conforms to the current "specification". I think, however, that this behavior should be changed (see my comment above).

**Comment by ratefuchs** [comment]
I have now implemented my proposal from above.

**Comment by mohrm** [comment]
I think it's pretty cool now:-)
